name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.38.5'
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_gz: "iVPN-Linux-x64-AppImage.tar"
  TARGET_NAME_deb: "iVPN-Debian-x64"
  TARGET_NAME_apk: "iVPN-Android"
  TARGET_NAME_aab: "iVPN-Android"
  TARGET_NAME_exe: "iVPN-Windows-Setup-x64"
  TARGET_NAME_msix: "iVPN-Windows-x64"
  TARGET_NAME_zip: "iVPN-Windows-Portable-x64"
  TARGET_NAME_dmg: "iVPN-MacOS"
  TARGET_NAME_pkg: "iVPN-MacOS-Installer"
  TARGET_NAME_ipa: "iVPN-iOS"

jobs:
  build:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
            targets: apk

          - platform: windows
            os: windows-latest
            targets: zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Clean up disk space
        if: startsWith(matrix.platform,'android')
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          rm -rf ~/.gradle/caches
          sudo apt-get autoremove -y
          sudo apt-get clean 
          df -h
      
      - name: Setup Java
        if: startsWith(matrix.platform,'android')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        if: startsWith(matrix.platform,'android')

      - name: Cache Gradle
        uses: actions/cache@v4
        if: startsWith(matrix.platform,'android')
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
                  
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Setup dependencies
        run: |
          make ${{ matrix.platform }}-install-deps  
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Setup Android Signing Properties
        if: ${{ inputs.upload-artifact && startsWith(matrix.platform,'android') }}
        run: |
          if [ -z "${{ secrets.ANDROID_SIGNING_KEY }}" ]; then
            echo "ANDROID_SIGNING_KEY is empty. Generating dummy keystore..."
            keytool -genkey -v -keystore android/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -storepass pass123 -keypass pass123 -dname "CN=iVPN, OU=iVPN, O=iVPN, C=US"
            echo "storeFile=$(pwd)/android/key.jks" > android/key.properties
            echo "storePassword=pass123" >> android/key.properties
            echo "keyPassword=pass123" >> android/key.properties
            echo "keyAlias=key" >> android/key.properties
          else
            echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android/key.jks
            echo "storeFile=$(pwd)/android/key.jks" > android/key.properties
            echo "storePassword=${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}" >> android/key.properties
            echo "keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> android/key.properties
            echo "keyAlias=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" >> android/key.properties
          fi

      - name: Setup Windows Signing Properties
        if: ${{ inputs.upload-artifact && startsWith(matrix.platform,'windows') }}
        run: |
            if ("${{ secrets.WINDOWS_SIGNING_KEY }}" -ne "") {
                [IO.File]::WriteAllBytes("windows\sign.pfx", [Convert]::FromBase64String("${{ secrets.WINDOWS_SIGNING_KEY }}"))
                (Get-Content "windows\packaging\msix\make_config.yaml") -replace '^certificate_password:.*$', 'certificate_password: ${{ secrets.WINDOWS_SIGNING_PASSWORD }}' | Set-Content "windows\packaging\msix\make_config.yaml"
            } else {
                Write-Host "WINDOWS_SIGNING_KEY is empty. Skipping Windows signing setup."
            }

      - name: Prepare for ${{ matrix.platform }}
        run: |
          make ${{ matrix.platform }}-prepare

      - name: Build ${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          make ${{ matrix.platform }}-release

      - name: Copy to out Windows
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          Get-ChildItem -Path dist -Recurse | Select-Object FullName
          New-Item -ItemType Directory -Path "out" -Force | Out-Null
          $targets = "${{ matrix.targets }}".Split(',')
          foreach ($ext in $targets) {
            $ext = $ext.Trim()
            $key = "TARGET_NAME_$ext"
            $targetName = (Get-Item "env:$key").Value

            $files = Get-ChildItem -Path dist -Recurse -Filter "*.$ext"

            foreach ($file in $files) {
                $destination = Join-Path -Path "out" -ChildPath "$targetName.$ext"
                Move-Item -Path $file.FullName -Destination $destination -Force
            }
          }
          Get-ChildItem -Path out
          
      - name: Copy to out Android APK
        if: matrix.platform == 'android-apk'
        run: |
          mkdir out
          ls -R ./build/app/outputs
          cp ./build/app/outputs/flutter-apk/*arm64-v8a*.apk out/${TARGET_NAME_apk}-arm64.apk || echo "no arm64 apk"
          cp ./build/app/outputs/flutter-apk/*armeabi-v7a*.apk out/${TARGET_NAME_apk}-arm7.apk || echo "no arm7 apk"
          cp ./build/app/outputs/flutter-apk/*x86_64*.apk out/${TARGET_NAME_apk}-x86_64.apk || echo "no x64 apk"
          cp ./build/app/outputs/flutter-apk/app-release.apk out/${TARGET_NAME_apk}-universal.apk || echo "no universal apk"

      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform}}
          path: ./out
          retention-days: 1

  update-draft:
    permissions: write-all
    if: ${{ inputs.upload-artifact }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: Display Files Structure
        run: |
          mkdir -p ./out
          ls -R ./out

      - name: prepare_release_message
        continue-on-error: true
        run: |
          set +e 
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md > release.md
          pip install gitchangelog pystache mustache markdown
          prelease=$(curl --silent "https://api.github.com/repos/hiddify/hiddify-app/releases/latest" | grep -Po '"tag_name": "\K([^"]*)') 
          echo -e "\n\n<details markdown=1><summary>All changes from $current to the latest commit:</summary>\n\n">>release.md
          gitchangelog "${prelease}.." >> release.md  2>&1 || echo "Error in gitchangelog"
          echo -e "\n\n</details>">>release.md

      - name: Create or Update Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./out/*
          name: 'draft'
          tag_name: 'draft'
          body_path: './release.md'
          prerelease: true

  upload-release:
    permissions: write-all
    if: ${{ inputs.upload-artifact && inputs.tag-name != 'draft' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: Display Files Structure
        run: |
          mkdir -p ./out
          ls -R ./out

      - name: prepare_release_message
        run: |
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md >> release.md

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          body_path: './release.md'
          files: ./out/*
